-- AI Trust Assessment: trade_questions cache, worker_trust_assessments scores, users.trade_competency_score
--
-- Forward-only migration. Apply manually through the bastion after review.
--
-- Service role for AI Lambdas. Password is generated by CDK in `jale/ai/db`;
-- set it manually after this migration, matching the existing jale_matching pattern:
--   ALTER ROLE jale_ai WITH PASSWORD '<generated>';
DO $$
BEGIN
  CREATE ROLE jale_ai LOGIN;
EXCEPTION
  WHEN duplicate_object THEN
    RAISE NOTICE 'role jale_ai already exists, skipping CREATE ROLE';
END;
$$;

-- trade_questions -----------------------------------------------------------
CREATE TABLE trade_questions (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  profession_key   TEXT        NOT NULL UNIQUE,
  profession_raw   TEXT        NOT NULL,
  questions        JSONB       NOT NULL,
  is_seeded        BOOLEAN     NOT NULL DEFAULT false,
  model_id         TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_trade_questions_profession_key ON trade_questions (profession_key);

GRANT SELECT, INSERT, UPDATE ON trade_questions TO jale_admin;
GRANT SELECT, INSERT, UPDATE ON trade_questions TO jale_ai;
GRANT SELECT ON trade_questions TO jale_whatsapp;

-- Seed known trades. Questions are scored descriptors, not WhatsApp button prompts.
-- Scorer pairs these with the worker's multiple-choice answer labels.
INSERT INTO trade_questions (profession_key, profession_raw, questions, is_seeded) VALUES
  ('electrician', 'electrician', '[
    {"q_en":"What type of electrical work do you specialize in?","q_es":"En que tipo de trabajo electrico te especializas?"},
    {"q_en":"What is your seniority level?","q_es":"Cual es tu nivel de experiencia?"},
    {"q_en":"What tasks do you do most as an electrician?","q_es":"Que tareas realizas con mas frecuencia como electricista?"}
  ]'::jsonb, true),
  ('plumber', 'plumber', '[
    {"q_en":"What type of plumbing work do you specialize in?","q_es":"En que tipo de trabajo de plomeria te especializas?"},
    {"q_en":"What is your seniority level?","q_es":"Cual es tu nivel de experiencia?"},
    {"q_en":"What tasks do you do most as a plumber?","q_es":"Que tareas realizas con mas frecuencia como plomero?"}
  ]'::jsonb, true),
  ('carpenter', 'carpenter', '[
    {"q_en":"What type of carpentry work do you specialize in?","q_es":"En que tipo de trabajo de carpinteria te especializas?"},
    {"q_en":"What is your seniority level?","q_es":"Cual es tu nivel de experiencia?"},
    {"q_en":"What tasks do you do most as a carpenter?","q_es":"Que tareas realizas con mas frecuencia como carpintero?"}
  ]'::jsonb, true),
  ('concrete', 'concrete', '[
    {"q_en":"What type of concrete work do you specialize in?","q_es":"En que tipo de trabajo de concreto te especializas?"},
    {"q_en":"What is your seniority level?","q_es":"Cual es tu nivel de experiencia?"},
    {"q_en":"What tasks do you do most in concrete work?","q_es":"Que tareas realizas con mas frecuencia en trabajo de concreto?"}
  ]'::jsonb, true),
  ('painting', 'painting', '[
    {"q_en":"What type of painting work do you specialize in?","q_es":"En que tipo de trabajo de pintura te especializas?"},
    {"q_en":"What is your seniority level?","q_es":"Cual es tu nivel de experiencia?"},
    {"q_en":"What tasks do you do most as a painter?","q_es":"Que tareas realizas con mas frecuencia como pintor?"}
  ]'::jsonb, true);

-- worker_trust_assessments --------------------------------------------------
CREATE TABLE worker_trust_assessments (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  profession_key      TEXT        NOT NULL,
  answers             JSONB       NOT NULL DEFAULT '[]'::jsonb,
  status              TEXT        NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','scoring','scored','failed')),
  competency_score    INTEGER     CHECK (competency_score BETWEEN 0 AND 100),
  score_components    JSONB,
  score_rationale     JSONB,
  rubric_version      TEXT,
  scoring_model_id    TEXT,
  scored_at           TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_worker_trust_assessments_user_id ON worker_trust_assessments (user_id);

-- Prevents duplicate active assessments per worker + profession.
-- Failed rows are excluded only after operator cleanup.
CREATE UNIQUE INDEX idx_worker_trust_assessments_active
  ON worker_trust_assessments (user_id, profession_key)
  WHERE status IN ('pending','scoring','scored');

ALTER TABLE worker_trust_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE worker_trust_assessments FORCE ROW LEVEL SECURITY;

CREATE POLICY wta_worker_own_rows ON worker_trust_assessments
  FOR ALL TO jale_admin
  USING (
    user_id = (
      SELECT id FROM users
      WHERE cognito_sub = current_setting('app.current_user_id', true)
    )
  );

CREATE POLICY wta_whatsapp_pending_rows ON worker_trust_assessments
  FOR ALL TO jale_whatsapp
  USING (true)
  WITH CHECK (status = 'pending');

CREATE POLICY wta_ai_service_rows ON worker_trust_assessments
  FOR ALL TO jale_ai
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON worker_trust_assessments TO jale_admin;
GRANT SELECT, INSERT, UPDATE ON worker_trust_assessments TO jale_ai;

-- jale_whatsapp: status + answers only, no score columns.
-- All queries from jale_whatsapp must name columns explicitly. SELECT * will error.
GRANT SELECT (id, user_id, profession_key, answers, status, created_at)
  ON worker_trust_assessments TO jale_whatsapp;
GRANT INSERT (id, user_id, profession_key, answers, status, created_at)
  ON worker_trust_assessments TO jale_whatsapp;

-- users: denormalized score column -----------------------------------------
ALTER TABLE users
  ADD COLUMN trade_competency_score INTEGER
    CHECK (trade_competency_score BETWEEN 0 AND 100);

GRANT SELECT (id, user_type) ON users TO jale_ai;
GRANT UPDATE (trade_competency_score) ON users TO jale_ai;

-- SELECT policy is required for UPDATE to find rows: PostgreSQL evaluates
-- SELECT policies first (visibility phase) before applying UPDATE USING.
-- Without this, UPDATE sees 0 rows even when the UPDATE policy permits the row.
CREATE POLICY users_ai_select ON users
  FOR SELECT TO jale_ai
  USING (user_type = 'worker');

CREATE POLICY users_ai_score_update ON users
  FOR UPDATE TO jale_ai
  USING (user_type = 'worker')
  WITH CHECK (user_type = 'worker');
